### PR TITLE
Add ability to control dismiss behavior after copy message

### PR DESCRIPTION
**Pull request by RoadToDream**
This commit add ability to control dismiss behavior after copy message.

Hi Finb,
Thank you for bringing this app to us, which greatly helps my entire workflow, thank you.
Not sure if this patch matches your vision towards Bark, but at least it provides additional control to users.

Best

### CODE REVIEW

**Comment by Finb** [comment]
I think instead of adding it as a default option, you can add it as a url request parameter.

This feature is very underused, don't even set up a tutorial card for it, just tell someone when they need it.

**Comment by RoadToDream** [comment]
> I think instead of adding it as a default option, you can add it as a url request parameter.
> 
> 
> 
> This feature is very underused, don't even set up a tutorial card for it, just tell someone when they need it.

Oh I didn't know it can be achieved by sending a url request parameter, that would be great! May I ask how to set up? 

My initial thought is that after copy the content from pulling down the notification, most user will turn to another app to paste and tend not to stay in the notification, so click outside to dismiss the notification feels a little non-intuitive.

**Comment by Finb** [comment]
All url parameters can be taken like this. (All parameter names will be converted to lowercase)
https://github.com/Finb/Bark/blob/dccd921b18e29bd602677119b58fd80e492b2151/NotificationServiceExtension/NotificationService.swift#L57

**Comment by RoadToDream** [comment]
I get it, thank you! 
It seems that I did not explain purpose of this commit clearly...
I intended to provide control that the notification will diss or not,
so mainly about 
`completion(.doNotDismiss)`
L66 in NotificationViewController.swift 
isArchive seems to control whether the message will be stored in message history 

But overall its a very personal request, so I will give all respects on your decision : ) 
Love the app and thank you for all the contribution.

**Pull request closed without merging**
